# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-08 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Please ignore this field', max_length=255, null=True)),
                ('commands', models.TextField(max_length=4000)),
                ('helptext', models.TextField(null=True)),
                ('network', models.TextField(null=True)),
                ('status', models.CharField(choices=[(b'A', b'Active'), (b'D', b'Deleted')], default=b'A', max_length=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ConfCreator',
                'verbose_name_plural': 'ConfCreators',
            },
        ),
    ]
