# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletest',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articletest',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleTest',
        ),
    ]
