# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161003_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='network',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
