# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-09 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20161005_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='factfile',
            new_name='factstatus',
        ),
        migrations.RemoveField(
            model_name='task',
            name='inventory',
        ),
        migrations.AlterField(
            model_name='task',
            name='network',
            field=models.CharField(default=b'EMC', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(b'A', b'Active'), (b'D', b'Deleted')], default=b'A', max_length=1),
        ),
    ]
